# vim:set ft=dockerfile:

FROM postgres

RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list

RUN apt-get update && apt-get install -y \
    postgresql-10-postgis-2.4 \
    rsync \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN apt-get update \
 && apt-get install -y wget \
    libboost-graph-dev \
    cmake \
    libcgal-dev \
    libperl-dev \
    g++ \
    postgresql-server-dev-10 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
 && mkdir /build_pgrouting

WORKDIR /build_pgrouting

RUN wget https://github.com/pgRouting/pgrouting/archive/v2.5.2.tar.gz && tar xzf v2.5.2.tar.gz

WORKDIR pgrouting-2.5.2

RUN mkdir build

WORKDIR build

RUN cmake ..\
 && make \
 && make install

WORKDIR /

RUN rm -rf /build_pgrouting